site.collections.modules.layout=module
site.collections.modules.from-data.id-key=title
quarkus.http.port=8081
%dev%.quarkus.http.port=8081
ttmc.uuid=${quarkus.uuid}
quarkus.log.category."io.quarkiverse.roq.frontmatter.deployment".level=DEBUG