name: Build & Deploy to Surge

on:
  push:
    branches: [ main, devfest, bdx-io ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Roq Site
        uses: quarkiverse/quarkus-roq@v1
        with:
          site-draft: 'true'
          site-future: 'true'
          github-pages: 'false'
          site-url: https://jtama-ttmc-${{ github.ref_name }}

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: |
          npx surge teardown https://jtama-ttmc-${{ github.ref_name }} --token ${{ secrets.SURGE_TOKEN }} || true
          
          npx surge ./target/roq \
            --domain https://jtama-ttmc-${{ github.ref_name }} \
            --token ${{ secrets.SURGE_TOKEN }}
